version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-app-network

volumes:
  mysql_data:

networks:
  spring-app-network:
